#!/usr/bin/env python3
"""Populate the database with sample TikTok videos for demo/testing purposes."""
import json
import urllib.request

API = "http://localhost:3000/api/videos"

videos = [
    {
        "title": "Receita de pão de queijo em 30 segundos",
        "videoUrl": "https://www.tiktok.com/@cozinhadavera/video/7100000000000000001",
        "authorUsername": "cozinhadavera",
        "authorName": "Vera Cozinha",
        "authorFollowers": 890000,
        "views": 2400000,
        "likes": 312000,
        "comments": 4500,
        "shares": 12000,
        "saves": 28000,
        "duration": 28,
        "publishDate": "2025-05-20T14:30:00Z",
        "hashtags": ["#receita", "#paodequeijo", "#comidabrasileira", "#fyp"],
        "description": "Pão de queijo mineiro crocante por fora e macio por dentro! Ingredientes na bio.",
        "language": "pt", "region": "BR",
        "soundName": "Música Ambiente Cozinha", "soundAuthor": "vera",
    },
    {
        "title": "Rotina de manhã produtiva (5h30)",
        "videoUrl": "https://www.tiktok.com/@produtividadehj/video/7100000000000000002",
        "authorUsername": "produtividadehj",
        "authorName": "Produtividade Hoje",
        "authorFollowers": 420000,
        "views": 856000,
        "likes": 78000,
        "comments": 2300,
        "shares": 5600,
        "saves": 41000,
        "duration": 47,
        "publishDate": "2025-06-28T07:00:00Z",
        "hashtags": ["#produtividade", "#rotinamatinal", "#5amclub", "#desenvolvimento"],
        "description": "Minha rotina das 5h30 que mudou minha vida. Salve para fazer amanhã!",
        "language": "pt", "region": "BR",
        "soundName": "Lo-fi Beats Morning", "soundAuthor": "lofigirl",
    },
    {
        "title": "Top 5 jogos mobile grátis de 2025",
        "videoUrl": "https://www.tiktok.com/@gamesmobilebr/video/7100000000000000003",
        "authorUsername": "gamesmobilebr",
        "authorName": "Games Mobile BR",
        "authorFollowers": 1200000,
        "views": 1900000,
        "likes": 145000,
        "comments": 8900,
        "shares": 22000,
        "saves": 15000,
        "duration": 60,
        "publishDate": "2025-06-10T18:45:00Z",
        "hashtags": ["#games", "#mobile", "#gaming", "#top5"],
        "description": "Os 5 melhores jogos grátis para celular em 2025. Quantos você já jogou?",
        "language": "pt", "region": "BR",
        "soundName": "Epic Gaming Mix", "soundAuthor": "epicsounds",
    },
    {
        "title": "Tutorial: corte pixie na navalha",
        "videoUrl": "https://www.tiktok.com/@estudiohelena/video/7100000000000000004",
        "authorUsername": "estudiohelena",
        "authorName": "Estúdio Helena",
        "authorFollowers": 540000,
        "views": 670000,
        "likes": 52000,
        "comments": 1800,
        "shares": 3400,
        "saves": 38000,
        "duration": 41,
        "publishDate": "2025-04-12T11:20:00Z",
        "hashtags": ["#cabelo", "#pixie", "#tutorial", "#cabeleireiro"],
        "description": "Corte pixie na navalha — passo a passo completo. Marque sua amiga que ama cabelo curto!",
        "language": "pt", "region": "BR",
        "soundName": "Lo-fi Salon", "soundAuthor": "salonbeats",
    },
    {
        "title": "Investindo R$100 todo mês em ações",
        "videoUrl": "https://www.tiktok.com/@financepratica/video/7100000000000000005",
        "authorUsername": "financepratica",
        "authorName": "Finança Prática",
        "authorFollowers": 670000,
        "views": 1100000,
        "likes": 89000,
        "comments": 5400,
        "shares": 18000,
        "saves": 92000,
        "duration": 53,
        "publishDate": "2025-06-30T09:15:00Z",
        "hashtags": ["#investimentos", "#acoes", "#financas", "#rendaextra"],
        "description": "Aportes mensais de R$100 podem virar quanto em 10 anos? Mostrei a conta.",
        "language": "pt", "region": "BR",
        "soundName": "Som Original", "soundAuthor": "financepratica",
    },
    {
        "title": "Mágica com moedas que impressiona",
        "videoUrl": "https://www.tiktok.com/@magiadoojoao/video/7100000000000000006",
        "authorUsername": "magiadoojoao",
        "authorName": "João Mágicas",
        "authorFollowers": 2300000,
        "views": 5800000,
        "likes": 890000,
        "comments": 15000,
        "shares": 67000,
        "saves": 24000,
        "duration": 19,
        "publishDate": "2025-07-01T20:30:00Z",
        "hashtags": ["#magica", "#ilusionismo", "#fyp", "#viral"],
        "description": "Como fiz a moeda sumir? Resposta nos comentários!",
        "language": "pt", "region": "BR",
        "soundName": "Magic Theme", "soundAuthor": "magicbeats",
    },
    {
        "title": "Viagem de 1 dia em Lisboa por R$200",
        "videoUrl": "https://www.tiktok.com/@viajandobarato/video/7100000000000000007",
        "authorUsername": "viajandobarato",
        "authorName": "Viajando Barato",
        "authorFollowers": 410000,
        "views": 920000,
        "likes": 76000,
        "comments": 3100,
        "shares": 14000,
        "saves": 58000,
        "duration": 58,
        "publishDate": "2025-03-25T16:00:00Z",
        "hashtags": ["#viagem", "#lisboa", "#portugal", "#dicasdeviagem"],
        "description": "Roteiro de 1 dia em Lisboa gastando pouco. Save para sua próxima viagem!",
        "language": "pt", "region": "PT",
        "soundName": "Portuguese Sunset", "soundAuthor": "travelbeats",
    },
    {
        "title": "Treino de pernas em casa (sem equipamento)",
        "videoUrl": "https://www.tiktok.com/@treinoemcasa/video/7100000000000000008",
        "authorUsername": "treinoemcasa",
        "authorName": "Treino em Casa",
        "authorFollowers": 780000,
        "views": 1450000,
        "likes": 178000,
        "comments": 4200,
        "shares": 9800,
        "saves": 76000,
        "duration": 35,
        "publishDate": "2025-06-05T06:30:00Z",
        "hashtags": ["#treino", "#fitness", "#pernas", "#casa"],
        "description": "4 exercícios para pernas sem equipamento. Repetir 3x. Vai!",
        "language": "pt", "region": "BR",
        "soundName": "Workout Beat", "soundAuthor": "fitnessbeats",
    },
]

for v in videos:
    body = json.dumps({"json": v, "runOcr": False, "runTranscribe": False}).encode()
    req = urllib.request.Request(API, data=body, headers={"Content-Type": "application/json"})
    try:
        res = urllib.request.urlopen(req)
        data = json.loads(res.read())
        print(f"✓ {v['title'][:50]} → {data['video']['id']}")
    except Exception as e:
        print(f"✗ {v['title'][:50]}: {e}")

print("\n=== Database populated ===")
